### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by bleonard252** [TeamFirework/SapphireBrowser#1]
```yaml
#note: do not modify this section
issue_ver: 1.0
sapphire_ver: unreleased
chromium_ver: unreleased
```

**Type:**
- [x] Bug Report: report an issue in Sapphire
- [ ] Feature Request: suggest a new feature
- [ ] Quality of Life Enhancement: request a small ease improvement

**Version:** Unreleased (Source Code)

**Summary:** This repository is encountering failed builds in Travis.

**Steps to reproduce:** 
1. Open [Travis](https://travis-ci.org/TeamFirework/SapphireBrowser)
2. Verify the [.travis.yml](/TeamFirework/SapphireBrowser/blob/master/.travis.yml)

Description
-----
Several build errors are occurring. This thread will track them until they're fixed.

**Comment by bleonard252** [comment]
Current error:
`gn.py: Could not find gn executable at: /home/travis/build/TeamFirework/SapphireBrowser/buildtools/linux64/gn`

Encountered during `./depot_tools/gn -v gen out/Default` in `install` stage

**Comment by bleonard252** [comment]
Current error:

```
Traceback (most recent call last):
  File "./depot_tools/gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "./depot_tools/gn.py", line 66, in main
    return subprocess.call([gn_path] + args[1:])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

Encountered during `./depot_tools/gn -v gen out/Default`

Potential solution: `chmod +x ./buildtools/linux64/gn`: will apply alongside deploy

**Comment by bleonard252** [comment]
Current error:
```
ERROR at //.gn:6:1: Unable to load "/home/travis/build/TeamFirework/SapphireBrowser/third_party/angle/dotfile_settings.gni".
import("//third_party/angle/dotfile_settings.gni")
^------------------------------------------------
```

Encountered during `./depot_tools/gn -v gen out/Default`

**Comment by bleonard252** [comment]
Any help sorting this out would be much appreciated!
